### PR TITLE
Better check for structs

### PR DESCRIPTION
**Pull request by JKRT**
If a user names a struct in all lowercase we will throw an error, this should maybe check that the type is a struct or abstract struct instead

### CODE REVIEW

**Comment by rai-nhdaly** [comment]
Haha yeah thanks I think this is a good suggestion!

I think the reason that this PR and your other PR https://github.com/RelationalAI-oss/Rematch.jl/pull/20 failed is because you're trying to check information about the _runtime type T_, but here inside the macro, `T` is just an _Expression_ or a _Symbol_.

What I think this should do is add the assertion you wrote into the _generated code_ produced by the macro. Glancing through the code, I think the way you do that is by pushing an `Expr` into the `asserts` array, as is done here:
https://github.com/JKRT/Rematch.jl/blob/76dfc7a25f6b98e3bfb2dac4199b68876ae9d7a8/src/Rematch.jl#L142

So in your case, i think that would be something like:
```julia
            push!(asserts, quote
                if !(isstructtype($T) || issabstracttype($T))
                    throw(AssertionError(...))
                end
            end)
```

**Comment by JKRT** [comment]
> 
> 
> Haha yeah thanks I think this is a good suggestion! The existing check is kind of silly!
> 
> I think the reason that this PR and your other PR #20 failed is because you're trying to check information about the _runtime type T_, but here inside the macro, `T` is just an _Expression_ or a _Symbol_.
> 
> What I think this should do is add the assertion you wrote into the _generated code_ produced by the macro. Glancing through the code, I think the way you do that is by pushing an `Expr` into the `asserts` array, as is done here:
> https://github.com/JKRT/Rematch.jl/blob/76dfc7a25f6b98e3bfb2dac4199b68876ae9d7a8/src/Rematch.jl#L142
> 
> So in your case, i think that would be something like:

> ```julia
>             push!(asserts, quote
>                 if !(isstructtype($T) || issabstracttype($T))
>                     throw(AssertionError(...))
>                 end
>             end)
> ```

@rai-nhdaly Great that we are in agreement 💯  I was just doing a quick and dirty fix hoping to get away with it. Sadly I did not :(,  However the above will not quote work. We should also check that it is not a function. So something like:  

`if  (T <: Function) && !(isstructtype($T) || issabstracttype($T)) ` Would that suffice?

**Comment by JKRT** [comment]
@rai-nhdaly  I updated it per your suggestions. It will still fail for later versions of Julia since the stuff I use is not really backward compatible. So compat needs to be changed for the next release

**Comment by JKRT** [comment]
@rai-nhdaly  Since you removed support for Julia 0.6 in #22 Maybe we can trigger the build again if you like my proposed changes

**Comment by rai-nhdaly** [comment]
I do, thanks. Can you merge master into your branch and then re-push? Thanks for your patience with this PR! :)

**Comment by JKRT** [comment]
Hi, 

Yes but I cannot promise that I have time to do this today. Maybe later tonight (I am in Sweden) : )

**Comment by rai-nhdaly** [comment]
:) No problem. Take your time!

**Comment by JKRT** [comment]
@rai-nhdaly I have rebased. Please restart my build 💯

**Comment by rai-nhdaly** [comment]
I think you need to push up your rebased branch to github. (via `git push --force`).

It doesn't show any changes since July (sorry again for our delay 😅)

**Comment by JKRT** [comment]
@rai-nhdaly fixed :)

**Comment by rai-nhdaly** [comment]
Awesome, thanks @JKRT!

I'm sorry this review got paused for a long time. :) Thanks for the contribution!

**Pull request merged**
